hotel/urls.py
'''package: hotel, description: urls'''
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from hotel import views

app_name = 'profiles'

urlpatterns = [
    path('', views.HotelListView.as_view(), name='hotel-list'),
    path('hotel/create', views.HotelCreateView.as_view(), name='hotel-create'),
    path('hotel/update/<slug:slug>', views.HotelUpdateView.as_view(), name='hotel-update'),
    path('hotel/detail/<slug:slug>', views.HotelDetailView.as_view(), name='hotel-detail'),
    path('hotel/<slug:slug>/create-address/', views.AddressCreateView.as_view(), name='address-create'),
    path('hotel/<slug:slug>/create_contact', views.HotelContactUpdateView.as_view(), name='contact-create'),
    path('hotel/<uuid:pk>/update-address', views.AddressUpdateView.as_view(), name='address-update'),
    path('hotel/delete/<slug:slug>', views.HotelDeleteView.as_view(), name='hotel-delete'),
    path('hotel/<slug:slug>/create-room', views.HotelRoomCreateView.as_view(), name='room-create'),
    path('hotel/<slug:slug>/update-room', views.HotelRoomUpdateView.as_view(), name='room-update'),
    path('subscribtions/accept/<uuid:pk>', views.SubscribtionUpdateView.as_view(), name='subscribtion-accept'),
    path('agreement/create/<slug:slug>', views.AgreementCreateView.as_view(), name='agreement-create'),
    path('agreement/update/<slug:slug>', views.AgreementUpdateView.as_view(), name='agreement-update'),
    path('agreement/<slug:slug>', views.AgreementView.as_view(), name='agreement'),
    path('basket/create/<slug:slug>', views.BasketCreateView.as_view(), name='basket-create')
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from search import views as search_views

urlpatterns = [
    path('', include('hotel.urls', namespace='hotel')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
#   path('search', search_views.search, name='search'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

hotel/models.py
'''
Package: hotel
description: hotel.models
'''
from uuid import uuid4
from django.db import models
from django.urls import reverse
from pytils.translit import slugify  # для перевода кирилицы

from sorl.thumbnail import ImageField

from address.models import Address

class Hotel(models.Model):
    '''
    Модель для отелей
    '''
    uuid = models.UUIDField(primary_key=True, default=uuid4)
    name = models.CharField(max_length=250, verbose_name='Название')
    address = models.ForeignKey(Address, null=True, on_delete=models.SET_NULL, verbose_name='Адрес отеля')
    photo = ImageField(blank=True, upload_to='hotel-logo', verbose_name='Логотип')
    slug = models.SlugField(max_length=250, editable=False, db_index=True, blank=True, verbose_name='ЧПУ')
    site = models.URLField(verbose_name='Сайт')
    created = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Дата добавления')
    edited = models.DateTimeField(auto_now=True, editable=False, verbose_name='Дата редактирования')

    def get_absolute_url(self):
        '''
        Возвращает абсолютный путь для HotelDetailView
        '''
        return reverse('profiles:hotel-detail', kwargs={'slug': self.slug})

    def __str__(self):
        return f'{self.name}'

    def to_dict(self):
        '''
        Предподгатавливает дикт для передачи в АПИ
        '''
        if self.address:
            address = str(self.address.uuid)
        else:
            address = None
        return  {
            'uuid': str(self.uuid),
            'name': self.name,
            'address': address,
            'site': self.site,
        }

    def save(self, *args, **kwargs): # pylint: disable=arguments-differ
        self.slug = slugify(f'{self.name} {self.uuid}')
        super(Hotel, self).save(*args, **kwargs)

    class Meta:
        unique_together = ['name', 'address']
        verbose_name = 'Отель'
        verbose_name_plural = 'Отели'


class Contact(models.Model):
    '''
    Модель для контактов отеля
    '''
    uuid = models.UUIDField(primary_key=True, default=uuid4)
    parent = models.ForeignKey(Hotel, on_delete=models.CASCADE, related_name='contacts', verbose_name='Название отеля')
    name = models.CharField(max_length=100, verbose_name='Cлужбa')
    phone = models.CharField(max_length=15, blank=True, verbose_name='Tелефон')
    email = models.EmailField(blank=True, verbose_name='email')
    created = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Дата добавления')
    edited = models.DateTimeField(auto_now=True, editable=False, verbose_name='Дата редактирования')

    def to_dict(self):
        '''
        Предподгатавливает дикт для передачи в АПИ
        '''
        return {
            'uuid': str(self.uuid),
            'parent': str(self.parent.uuid),
            'name': self.name,
            'phone': self.phone,
            'email': self.email,
        }

    def __str__(self):
        return f'{self.name}, {self.phone}, {self.email}'
    
    class Meta:
        unique_together = ['parent', 'name']
        verbose_name = 'Контакты службы'
        verbose_name_plural = 'Контакты служб'


class Room(models.Model):
    '''
    Модель для номеров
    '''
    BED_TYPE = (
        ('Single', 'Single'),
        ('Double', 'Double'),
        ('Triple', 'Triple')
    )
    ROOM_TYPE = (
        ('Lux', 'Lux'),
        ('Lux/2', 'Lux/2'),
        ('Standartx2', 'Standartx2'),
        ('Standart', 'Standart')
    )
    uuid = models.UUIDField(primary_key=True, default=uuid4)
    parent = models.ForeignKey(Hotel, on_delete=models.CASCADE, related_name='rooms', verbose_name='Отель')
    desc = models.CharField(max_length=100, blank=True, verbose_name='Краткое описание')
    bed_type = models.CharField(max_length=6, choices=BED_TYPE, null=False, blank=False, verbose_name='Тип кровати')
    room_type = models.CharField(max_length=10, choices=ROOM_TYPE, null=False, blank=False, verbose_name='Тип номера')
    created = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Дата добавления')
    edited = models.DateTimeField(auto_now=True, editable=False, verbose_name='Дата редактирования')

    def to_dict(self):
        '''
        Предподгатавливает дикт для передачи в АПИ
        '''
        return {
            'uuid': str(self.uuid),
            'parent': str(self.parent.uuid),
            'desc': self.desc,
            'bed_type': self.bed_type,
            'room_type': self.room_type,
        }

    def __str__(self):
        return f'{self.parent.name}: {self.room_type}, {self.bed_type}'

    class Meta:
        verbose_name = 'Номер'
        verbose_name_plural = 'Номера'

class Contragent(models.Model):
    '''
    Модель для контрагентов
    '''
    uuid = models.UUIDField(primary_key=True, default=uuid4)
    name = models.CharField(max_length=250, default='NO NAME', verbose_name='Название контрагента')
    address = models.ForeignKey(
        Address,
        on_delete=models.SET_NULL,
        related_name='agencies',
        null=True,
        blank=True,
        verbose_name='Адрес контрагента'
    )
    slug = models.SlugField(editable=False, db_index=True, blank=True, verbose_name='ЧПУ')
    site = models.URLField(blank=True, verbose_name='Адрес сайта')
    photo = models.ImageField(upload_to='contr', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Дата добавления')
    edited = models.DateTimeField(auto_now=True, editable=False, verbose_name='Дата редактирования')

    def __str__(self):
        return self.name

    def to_dict(self):
        '''
        Предподгатавливает дикт для передачи в АПИ
        '''
        return {
            'uuid': self.uuid,
            'name': self.name,
            'address': self.address.uuid,
            'site': self.site
        }

    class Meta:
        verbose_name = 'Контрагента'
        verbose_name_plural = 'Контрагенты'
        unique_together = ['name', 'address']

class Agreement(models.Model):
    '''
    Модель для сделок
    '''
    STATUS = (
        (0, 'None'),
        (1, 'Approved'),
        (2, 'Canceled')
    )
    uuid = models.UUIDField(primary_key=True, default=uuid4, )
    slug = models.SlugField(max_length=8, db_index=True, verbose_name='Ref Key')
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, related_name='agreement_hotel')
    agent = models.ForeignKey(Contragent, on_delete=models.CASCADE, null=True, related_name='agreement_contragent')
    process_status = models.PositiveSmallIntegerField(choices=STATUS, default=0, verbose_name='Статус брони')
    created = models.DateTimeField(auto_now_add=True, editable=False)
    edited = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.slug

    def to_dict(self):
        '''
        Предподгатавливает дикт для передачи в АПИ
        '''
        if self.agent is not None:
            return {
                'uuid': str(self.uuid),
                'slug': self.slug,
                'hotel': str(self.hotel.uuid),
                'agent': str(self.agent.uuid),
                'process_status': self.process_status,
            }
        return  {
            'uuid': str(self.uuid),
            'slug': self.slug,
            'hotel': str(self.hotel.uuid),
            'process_status': self.process_status,
        }
        

    class Meta:
        verbose_name = 'Бронь'
        verbose_name_plural = 'Бронирование'


class Ticket(models.Model):
    '''
    Модель для тикетов
    '''
    STATUS = (
        (0, 'None'),
        (1, 'Approved'),
        (2, 'Canceled')
    )
    uuid = models.UUIDField(primary_key=True, default=uuid4)
    parent = models.ForeignKey(Agreement,
                               db_index=True,
                               on_delete=models.CASCADE,
                               related_name='tickets')
    contragent_from = models.UUIDField(verbose_name='От кого')
    contragent_to = models.UUIDField(verbose_name='Кому')
    status = models.PositiveSmallIntegerField(choices=STATUS, default=0, verbose_name='Process status')
    created = models.DateTimeField(auto_now_add=True, editable=False)
    edited = models.DateTimeField(auto_now=True, editable=False)

    def to_dict(self):
        '''
        Предподгатавливает дикт для передачи в АПИ
        '''
        return {
            'uuid': str(self.uuid),
            'contragent_from': str(self.contragent_from),
            'contragent_to': str(self.contragent_to),
            'status': self.status,
            'parent': str(self.parent.uuid)
        }

    class Meta:
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'
        ordering = ['-created']


class TicketItem(models.Model):
    '''
    Модель для содержимого тикета
    '''
    uuid = models.UUIDField(primary_key=True, default=uuid4)
    parent = models.ForeignKey(Agreement,
                               on_delete=models.CASCADE,
                               db_index=True,
                               related_name='items',
                               verbose_name='Отель')
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='item_room', verbose_name='номер')
    date_start = models.DateTimeField(verbose_name='дата заезда')
    date_end = models.DateTimeField(verbose_name='дата выезда')

    def to_dict(self):
        '''
        Предподгатавливает дикт для передачи в АПИ
        '''
        return {
            'uuid': str(self.uuid),
            'parent': str(self.parent.uuid),
            'room': str(self.room.uuid),
            'date_start': str(self.date_start),
            'date_end': str(self.date_end),
        }

    def __str__(self):
        return str(self.uuid)

    class Meta:
        verbose_name = 'Объект'
        verbose_name_plural = 'Объекты'


class Basket(models.Model):
    """
    Таблица для Basket
    """
    ROOM_TYPE = Room.ROOM_TYPE
    BED_TYPE = Room.BED_TYPE

hotel/templates/hotel/address_form.html
{% extends 'hotel/hotel_form.html' %}

{% block page_name %}
Добавление отеля
{% endblock %}

{% block crumb %}
{{ block.super }}
{% if 'create' in request.path %}
<li><a href="{% url 'hotel:address-create' hotel_slug %}">Добавление адреса</a></li>
{% endif %}
{% endblock %}

{% block content %}
<div class="col-md-6 col-md-offset-3 ">
  <div class="box box-default" data-select2-id="16">
    <div class="box-header with-border">
      <h3 class="box-title"></h3>
      <div class="box-tools pull-right">
	<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body" data-select2-id="15">
      <form class="form-horizontal" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.uuid}}

	<div class="form-group">
	  {{form.country.errors}}
	  <label for="id_{{form.country.name}}" class="col-sm-3 control-label">{{form.country.label}}</label>
	  <div class="col-sm-8">
	    {{ form.country }}
	  </div>
	</div>

	<div class="form-group">
	  {{form.region.errors}}
	  <label for="id_{{form.region.name}}" class="col-sm-3 control-label">{{form.region.label}}</label>
	  <div class="col-sm-8">
	    {{ form.region }}
	  </div>
	</div>
	
	<div class="form-group">
	  {{form.city.errors}}
	  <label for="id_{{form.city.name}}" class="col-sm-3 control-label">{{form.city.label}}</label>
	  <div class="col-sm-8">
	      {{ form.city }}
	  </div>
	</div>
	
	<div class="form-group">
	  {{form.area.errors}}
	  <label for="id_{{form.area.name}}" class="col-sm-3 control-label">{{form.area.label}}</label>
	  <div class="col-sm-8">
	    {{ form.area }}
	  </div>
	</div>
	
	<div class="form-group">
	  {{form.street.errors}}
	  <label for="id_{{form.street.name}}" class="col-sm-3 control-label">{{form.street.label}}</label>
	  <div class="col-sm-8">
	    {{ form.street }}
	  </div>
	</div>
	
	<div class="form-group">
	  {{form.house.errors}}
	  <label for="id_{{form.house.name}}" class="col-sm-3 control-label">{{form.house.label}}</label>
	  <div class="col-sm-8">
	    {{ form.house }}
	  </div>
	</div>
	
	<div class="form-group">
	  {{form.flat.errors}}
	  <label for="id_{{form.flat.name}}" class="col-sm-3 control-label">{{form.flat.label}}</label>
	  <div class="col-sm-8">
	    {{ form.flat }}
	  </div>
	</div>
	
	<div class="form-group">
	  {{form.index.errors}}
	  <label for="id_{{form.index.name}}" class="col-sm-3 control-label">{{form.index.label}}</label>
	  <div class="col-sm-8">
	    {{ form.index }}
	  </div>
	</div>
	
	<div class="box-footer">
	  <a href="{% url 'hotel:hotel-list'%}" class="btn btn-default">Отмена</a>
	  <button type="submit" class="btn btn-info pull-right">Далее</button>
	</div>
	</div>
    </form>
    <!-- /.form-->
  </div>
  <!-- /.box-body -->
</div>
{% endblock %}
  

hotel/templates/hotel/agreement_create_form.html
{% extends 'hotel/hotel_detail.html' %}
{% load hotel_tags %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  {{form}}
</form>
{% endblock%}

hotel/templates/hotel/basket_form.html
<form method="POST">
  {% csrf_token%}
  {{form}}
</form>

hotel/templates/hotel/contact_form.html
{% extends 'hotel/index.html' %}

{% load static%}

{% block page_name %}
Добавление отеля
{% endblock %}

{% block crumb %}
{{ block.super }}
<li><a href="{% url 'hotel:contact-create' object.slug %}">Добавление контактов</a></li>
{% endblock %}

{% block content %}
<div class="col-md-6 col-md-offset-3 ">
  <div class="box box-default" data-select2-id="16">
    <div class="box-header with-border">
      <h3 class="box-title"></h3>
      <div class="box-tools pull-right">
	<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body" data-select2-id="15">
      <form class="form-horizontal" method="POST">
	<div id="form_set">
	  {% csrf_token %}
	  {{ form.management_form }}
	  {% for f in form %}
	  <div class="row">
	    <div class="col-md-3 col-md-offset-1">
	      <div class="form-group">
		<label for="id_{{f.name.name}}" class="col-md-3 control-label">{{f.name.label}}</label>
		{{f.name.errors}}
		{{ f.name }}
	      </div>
	    </div>
	    
	    <div class="col-md-3">
	      <div class="form-group">
		<label for="id_{{f.email.name}}" class="col-md-3 control-label">{{f.email.label}}</label>
		{{f.email.errors}}
		{{ f.email }}
	      </div>
	    </div>
	    
	    <div class="col-md-3">
	      <div class="form-group">
		<label for="id_{{f.phone.name}}" class="col-md-3 control-label">{{f.phone.label}}</label>
		{{f.phone.errors}}
		{{ f.phone }}
	      </div>
	    </div>
	    {{f.uuid}}
	  </div>
	  <hr>
	  {% endfor %}
	  <button type="submit" class="btn btn-info">Добавить</button>
	</div>
      </form>
      <div class="box-footer">
	<a href="{% url 'hotel:hotel-list'%}" class="btn btn-default">Отмена</a>
	<a href="{% url 'hotel:hotel-detail' object.slug %}" class="btn btn-primary pull-right">Далее</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

hotel/templates/hotel/hotel_form.html
{% extends 'hotel/index.html' %}

{% block page_name %}
Добавление отеля
{% endblock %}

{% block crumb %}
{{ block.super }}
<li><a href="{% url 'hotel:hotel-create' %}">Добавление отеля</a></li>
{% endblock %}

{% block content%}
<div class="col-md-6 col-md-offset-3 ">
  <div class="box box-default" data-select2-id="16">
    <div class="box-header with-border">
      <h3 class="box-title"></h3>
      <div class="box-tools pull-right">
	<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
      </div>
    </div>
    <!-- /.box-header -->
    
    <div class="box-body" data-select2-id="15">
      <form class="form-horizontal" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	<div class="form-group">
	  {{form.name.errors}}
	  <label for="id_{{form.name.name}}" class="col-sm-3 control-label">{{form.name.label}}</label>
	  <div class="col-sm-8">
	    {{ form.name }}
	  </div>
	</div>
	
	
    
	<div class="form-group">
	  {{form.site.errors}}
	  <label for="id_{{form.site.name}}" class="col-sm-3 control-label">{{form.site.label}}</label>
	  <div class="col-sm-8">
	    {{ form.site }}
	  </div>
	</div>
	
	
    
	<div class="form-group">
	  {{form.photo.errors}}
	  <label for="id_{{form.photo.name}}" class="col-sm-3 control-label">{{form.photo.label}}</label>
	  <div class="col-sm-8">
	    {{ form.photo }}
	  </div>
	</div>
	
	<div class="box-footer">
	  <a href="{% url 'hotel:hotel-list'%}" class="btn btn-default">Отмена</a>
	  <button type="submit" class="btn btn-info pull-right">Далее</button>
	</div>
      </form>
      <!-- /.form-group -->
      
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>
</div>


{% endblock%}

hotel/templates/hotel/hotel_list.html
{% extends 'hotel/index.html' %}
{% load i18n thumbnail hotel_tags%}


{% block infobox %}

{% if perms.hotel.add_hotel %}
<div class="col-lg-3 col-xs-6">
  <!-- small box -->
  <div class="small-box bg-aqua">
    <div class="inner">
      <h3>Отель</h3>
      <p>Добавить отель</p>
    </div>
    <div class="icon">
      <i class="ion ion-compass"></i>
    </div>
    <a href="{% url 'hotel:hotel-create' %}" class="small-box-footer">подробнее <i class="fa fa-arrow-circle-right"></i></a>
  </div>
</div>

{% endif %}

{% endblock %}


{% block content %}
<div class="row">
  <div class="col-xs-12">
    {% for item in hotel_list %}
    <div class="col-md-4">
      <!-- Widget: user widget style 1 -->
      <div class="box box-widget widget-user" onclick="location.href='{% url 'hotel:hotel-detail' item.slug %}'">
	<!-- Add the bg color to the header using any of the bg-*1 classes -->
	<div class="widget-user-header bg-aqua-active">
	  <h3 class="widget-user-username">{{ item.name }}</h3>
	  <h5>{% address_by_uuid item.address_id %}</h5>
	</div>
	<div class="widget-user-image">
	  {% thumbnail item.photo "200x200" crop="center" as im %}
	  <img class="img-circle" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
	  {% endthumbnail %}	  
	</div>
	<div class="box-footer">
	  <div class="row">
	    <div class="col-sm-4 border-right">
	      <div class="description-block">
		<h5 class="description-header">3,200</h5>
		<span class="description-text">Запросы</span>
	      </div>
	      <!-- /.description-block -->
	    </div>
	    <!-- /.col -->
	    <div class="col-sm-4 border-right">
	      <div class="description-block">
		<h5 class="description-header">13,000</h5>
		<span class="description-text">Брони</span>
	      </div>
	      <!-- /.description-block -->
	    </div>
	    <!-- /.col -->
	    <div class="col-sm-4">
	      <div class="description-block">
		<h5 class="description-header">35</h5>
		<span class="description-text">Партнеры</span>
	      </div>
	      <!-- /.description-block -->
	    </div>
	    <!-- /.col -->
	  </div>
	  <!-- /.row -->
	</div>
      </div>
      <!-- /.widget-user -->
    </div>
    {% endfor %}


  </div>
</div>
{% endblock %}

hotel/templates/hotel/index.html
{% extends 'base.html' %}

hotel/templates/hotel/room_form.html
{% extends 'hotel/index.html' %}

{% load static%}

{% block page_name %}
Добавление номера
{% endblock %}



{% block content %}
<div class="col-md-6 col-md-offset-3  ">
  <div class="box box-default" data-select2-id="16">
    <div class="box-header with-border">
      <h3 class="box-title"></h3>
      <div class="box-tools pull-right">
	<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <form class="form-horizontal" method="POST" enctype="multipart/formdata">
	{% csrf_token %}
	{{form.errors}}
	{{form.uuid}}
	<input type="hidden" name="parent" value="{{hotel.uuid}}">
	<div class="form-group">
	  <label for="id_{{form.count.name}}" class="col-sm-3 control-label">Задайте количество</label>
	  {{forms.count.errors}}
	  <div class="col-sm-8">
	    {{ form.count }}
	  </div>
	</div>
    
	
	<div class="form-group">
	  <label for="id_{{form.desc.name}}" class="col-sm-3 control-label">{{form.desc.label}}</label>
	  {{form.desc.errors}}
	  <div class="col-sm-8">
	    {{ form.desc }}
	  </div>
	</div>
	
	<div class="form-group">
	  <label for="id_{{form.room_type.name}}" class="col-sm-3 control-label">{{form.room_type.label}}</label>
	  {{form.room_type.errors}}
	  <div class="col-sm-8">
	    {{ form.room_type }}
	  </div>
	</div>
	
	<div class="form-group">
	  <label for="id_{{form.bed_type.name}}" class="col-sm-3 control-label">{{form.bed_type.label}}</label>
	  {{form.bed_type.errors}}
	  <div class="col-sm-8">
	    {{ form.bed_type }}
	  </div>
	</div>
	<button type="submit" class="btn btn-info pull-right">Далее</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

hotel/templates/hotel/ticket_list.html
{% extends 'hotel/index.html' %}
{% load hotel_tags %}
{% block content %}
<div class="row">
  {% for ticket in object_list %}
  <div class="col-md-9">
    <div class="box">
      <div class="box-header with-boarder">
	<div class="pull-right box-tools">
	  <button type="button" class="btn btn-primary btn-sm daterange pull-right" data-toggle="tooltip" title="" data-original-title="Date range">
	    <i class="fa fa-calendar"></i></button>
	  <button type="button" class="btn btn-primary btn-sm pull-right" data-widget="collapse" data-toggle="tooltip" title="" style="margin-right: 5px;" data-original-title="Collapse">
	    <i class="fa fa-minus"></i></button>
	</div>
	<h3 class="box_title">Number {{ticket.slug}}</h3>
        <div class="box-body table-responsive no-padding">
	  <div class="box">
	    <div class="box-header">
	      <h3 class="box-title">
		Статус -
		{% if ticket.status == 1 %}
		подтверждено
		{% elif ticket.status == 2 %}
		отклонено
		{% else %}
		на рассмотрении
		{% endif %}
	      </h3>
	      {% if 'status_none' in request.path %}
	      <form action="{% url 'hotel:ticket-create' %}" method="post">
		{% csrf_token %}
		<input type="hidden" name="slug" value="{{ticket.slug}}">
		<input type="hidden" name="contragent_to" id="id_contragent_to" value="{{ticket.contragent_from}}">
		<input type="hidden" name="contragent_from" id="id_contragent_from" value="{{ticket.contragent_to}}">
		<input type="hidden" name="status" value="1">
		{{ formset }}
		<button class="btn btn-primary" type="submit">Принять</button>
	      </form>
	      <form action="{% url 'hotel:ticket-create' %}" method="post">
		{% csrf_token %}
		<input type="hidden" name="slug" value="{{ticket.slug}}">
		<input type="hidden" name="contragent_to" id="id_contragent_to" value="{{ticket.contragent_from}}">
		<input type="hidden" name="contragent_from" id="id_contragent_from" value="{{ticket.contragent_to}}">
		<input type="hidden" name="status" value="2">
		{{ formset }}
		<button class="btn btn-danger" type="submit">Отклонить</button>
	      </form>
	      {% endif %}
	    </div>
	    <!-- /.box-header -->
	    <div class="box-body no-padding">
	      <table class="table table-striped">
		<tbody><tr>
		    <th>Номер</th>
		    <th>Тип номера</th>
		    <th>Тип кровати</th>
		    <th>Дата - с</th>
		    <th>Дата - по</th>
		  </tr>
		  {% for item in ticket.item_set.all%}
		  <tr>
		    <td>{% room_by_uuid item.room as room %} {{ room.number }}</td>
		    <td>{{ room.room_type}}</td>
		    <td>{{ room.bed_type }}</td>
		    <td>{{ item.date_start}}</td>
		    <td>{{ item.date_end }}</td>
		  </tr>
		  {% endfor %}
	      </tbody></table>

	    </div>
	    <!-- /.box-body -->
	  </div>
	</div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}